services:
  backend_server:
    depends_on:
      db_server:
        condition: service_healthy
    ports:
      - "8080:8080"
    build: .
    environment:
      - DBNAME=proway
      - DBUSER=proway
      - DBPASS=proway
      - DBHOST=db_server
    volumes:
      - /home/aluno/proway-back:/code

  db_server:
    image: postgres:13.2
    environment:
      - POSTGRES_DB=proway
      - POSTGRES_USER=proway
      - POSTGRES_PASSWORD=proway
      - PGDATA=/var/lib/postgresql/data/db-files/
    healthcheck:
      test: [ "CMD", "pg_isready", "-U", "proway" ]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - /tmp:/var/lib/postgresql/data

volumes:
  var_postgresql:
