
services:
  server:
    depends_on:
      db_server:
        condition: service_healthy
    ports:
      - "8000:8000"
    build: .
    environment:
      - DBNAME=proway
      - DBUSER=proway
      - DBPASS=proway
      - DBHOST=db_server
      - DJANGO_SUPERUSER_PASSWORD=proway
      - DJANGO_SUPERUSER_USERNAME=proway
      - DJANGO_SUPERUSER_EMAIL=dartanghan@gmail.com
    networks:
      - rede_sistema_alunos

  db_server:
    image: postgres:13.2
    environment:
      - POSTGRES_DB=proway
      - POSTGRES_USER=proway
      - POSTGRES_PASSWORD=proway
    volumes:
      - db_data:/var/lib/postgresql/data
    healthcheck: 
      test: ["CMD", "pg_isready", "-U", "proway"] 
      interval: 10s 
      timeout: 5s 
      retries: 5
    networks:
      - rede_sistema_alunos

volumes:
 db_data:

networks:
  rede_sistema_alunos:
    driver: bridge